import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button, Container } from "@mui/material";
import tw, { styled } from "twin.macro";
import React, { ReactElement, useEffect } from "react";
import Layout from "../components/Layout";
import { useAuthenticator } from "@aws-amplify/ui-react";
import { Router, useRouter } from "next/router";

export const getServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/hello");
  const data = await res.json();
  if (!data) {
    return {
      notFound: true,
    };
  }
  return {
    props: data,
  };
};

type NextPageWithLayout<T> = NextPage<T> & {
  getLayout?: (page: ReactElement) => ReactElement;
};

const MainContainer = styled(Container)(() => [tw`text-center`]);

const Home: NextPageWithLayout<{ name: string }> = ({ name }) => {
  const { user, signOut } = useAuthenticator((context) => [context.user]);
  const router = useRouter();
  return (
    <MainContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>안녕 여러분!!</h1>
        {user ? (
          <>
            <h2>Welcome, {user!.username}!</h2>
            <Button variant="contained" onClick={signOut}>
              Sign Out
            </Button>
          </>
        ) : (
          <>
            <h2>you should login</h2>
            <Button variant="contained" onClick={() => router.push("/signin")}>
              로그인하러가자
            </Button>
          </>
        )}
      </main>
    </MainContainer>
  );
};
export default Home;

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};
